### ISSUE TITLE
Add irregular z-grid

### ISSUE THREAD

**Issue by txs156** [navidcy/ASC-idealised#13]
Need to add a z grid which varies in the vertical from 13m to 100m dz over 53 levels (following TS14).

**Comment by navidcy** [comment]
We can do that by prescribing a 53-level array with the z-faces (including z=0 and z=-Lz) or by prescribing a function that will give us the location of those faces.

See, https://clima.github.io/OceananigansDocumentation/stable/model_setup/grids/#Grids-with-non-regular-spacing-in-some-of-the-directions

**Comment by navidcy** [comment]
If we write a function `zfaces(k)` then the grid constructor will assume that `k` varies from 1 to `Nz+1` so we need to ensure that `zfaces(1) = -Lz` and `zfaces(Nz+1) = 0`.
